server:
  port: 8082
spring:
  application:
    name: payroll-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payroll_db
    username: postgres 
    password: root 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  web:
    resources:
      add-mappings: false

rabbitmq:
  exchange:
    employee: employee.exchange
  queue:
    employee:
      events: employee.events.queue
